config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  # Resources gives you portfolio_items/show and index but overrides the path to 'work'
  # Resources is for a thing that has a lot/ it's gonna be in the db
  resources :case_studies, only: [:show, :index], path: 'work', param: :slug
  # API route for video interactions
  resources :interactions, only: [:index, :create]

  # Custom routing: when you go to /contact, contacts#new handles the request
  get '/contact', to: 'contacts#new'
  post '/contacts', to: 'contacts#create'
  get '/about', to: 'pages#about'

  namespace :admin do
    root 'case_studies#index'
    resources :case_studies, param: :slug do
      resources :code_highlights
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  if Rails.env.development?
    mount Localtower::Engine, at: "localtower"
  end
end

app/models/case_study.rb
class CaseStudy < ApplicationRecord

  # Relations
  has_many :code_highlights

  # Scopes

  # Validations
  validates :slug, :title, :video_url, :description, :description_image,
    :challenges, :challenges_image, :position, :technologies, presence: true

  # Attachments

  has_attached_file :description_image, styles: {
    thumb: "200x200>",
    hero: "2880x1800>"
  }
  validates_attachment_content_type :description_image, content_type: /\Aimage\/.*\Z/

  has_attached_file :challenges_image, styles: {
    thumb: "200x200>",
    hero: "2880x1800>"
  }
  validates_attachment_content_type :challenges_image, content_type: /\Aimage\/.*\Z/

  has_attached_file :technologies_image, styles: {
    thumb: "200x200>",
    hero: "2880x1800>"
  }
  validates_attachment_content_type :technologies_image, content_type: /\Aimage\/.*\Z/

  # Callbacks

  # Methods
  def to_param
    slug
  end

end

app/controllers/admin/case_studies_controller.rb
class Admin::CaseStudiesController < Admin::BaseController

  def index
    @case_studies = CaseStudy.all
  end

  def new
    @case_study = CaseStudy.new
  end

  def create
    @case_study = CaseStudy.new(case_study_params)
    if @case_study.save
      redirect_to edit_admin_case_study_url(@case_study)
    else
      render :new
    end
  end

  def edit
    @case_study = CaseStudy.find_by(slug: params[:slug])
  end

  def update
    @case_study = CaseStudy.find_by(slug: params[:slug])
    if @case_study.update(case_study_params)
      redirect_to edit_admin_case_study_url(@case_study)
    else
      render :edit
    end
  end

  def destroy
    @case_study = CaseStudy.find_by(slug: params[:slug])
    @case_study.destroy
    redirect_to admin_case_studies_url
  end

  private

  def case_study_params
    params.require(:case_study).permit(:slug, :title, :video_url, :github_url,
      :site_url, :description, :description_image, :one_liner, :technologies,
      :technologies_image, :challenges, :challenges_image, :position
    )
  end

end

app/controllers/case_studies_controller.rb
class CaseStudiesController < ApplicationController
  def index
    @case_studies_props = CaseStudy.limit(5).order(position: :desc).map do |case_study|
      case_study.attributes.merge(
       "image_url" => case_study.description_image.url(:hero),
       "technologies" => case_study.technologies.split(",").first(3).map(&:strip).join(' · ')
      )
    end
  end

  def show
    case_study = CaseStudy.find_by(slug: params[:slug])
    @case_study_props = case_study.attributes.merge(
      description_image_url: case_study.description_image.url(:hero),
      technologies_image_url: case_study.technologies_image.url(:hero),
      challenges_image_url: case_study.challenges_image.url(:hero)
    )

    @code_highlights_props = case_study.code_highlights.order(:position).map do |code_highlight|
      code_highlight.attributes.merge(
        image_url: code_highlight.image.url(:hero)
      )
    end

    @more_case_studies_props = CaseStudy.where.not(id: case_study.id).
      order('random()').limit(2).map do |case_study|
        case_study.attributes.merge(
          image_url: case_study.description_image.url(:hero)
        )
      end
  end
end

app/views/admin/case_studies/_form.html.haml
= simple_form_for(@case_study, url: [:admin, @case_study]) do |f|
  = f.input :position, required: true
  = f.input :title
  = f.input :github_url, as: :url
  = f.input :site_url, as: :url
  = f.input :slug
  = f.input :video_url, as: :url
  = f.input :one_liner

  - [:description, :technologies, :challenges].each do |field|
    = f.input field
    - if @case_study.send("#{field}_image").present?
      = image_tag @case_study.send("#{field}_image").url(:thumb)
      = link_to 'Original', @case_study.send("#{field}_image").url
    = f.input "#{field}_image", as: :file

  .form-group
    = f.submit class: "btn btn-primary"
    = link_to "Cancel", admin_case_studies_url, class: "btn btn-secondary"

app/views/admin/case_studies/edit.html.haml
%h2 Editing #{@case_study.title}

= render partial: 'form'

app/views/admin/case_studies/index.html.haml
%h2 Case Studies

= link_to 'New Case Study', new_admin_case_study_url, class: 'btn btn-primary'

%table.table
  %tr
    %th Position
    %th Title
    %th Actions
  - @case_studies.each do |case_study|
    %tr
      %td= case_study.position
      %td= case_study.title
      %td
        = link_to("Edit", edit_admin_case_study_url(case_study), class: 'btn btn-secondary')
        = link_to("Code", admin_case_study_code_highlights_url(case_study), class: 'btn btn-secondary')
        = link_to("Delete", admin_case_study_url(case_study), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger')

app/views/admin/case_studies/new.html.haml
%h2 New Case Study

= render partial: 'form'