config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  # Resources gives you portfolio_items/show and index but overrides the path to 'work'
  # Resources is for a thing that has a lot/ it's gonna be in the db
  resources :case_studies, only: [:show, :index], path: 'work', param: :slug
  # API route for video interactions
  resources :interactions, only: [:index, :create]

  # Custom routing: when you go to /contact, contacts#new handles the request
  get '/contact', to: 'contacts#new'
  post '/contacts', to: 'contacts#create'
  get '/about', to: 'pages#about'

  namespace :admin do
    root 'case_studies#index'
    resources :case_studies, param: :slug do
      resources :code_highlights
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  if Rails.env.development?
    mount Localtower::Engine, at: "localtower"
  end
end

app/models/code_highlight.rb
class CodeHighlight < ApplicationRecord

  # Relations
  belongs_to :case_study

  # Scopes

  # Validations
  validates :image, :caption, :position, presence: true

  # Attachments

  has_attached_file :image, styles: {
    thumb: "200x200>",
    hero: "2880x1800>"
  }
  
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  # Callbacks

  # Methods

end

app/controllers/admin/code_highlights_controller.rb
class Admin::CodeHighlightsController < Admin::BaseController

  before_action :load_case_study

  def index
    @code_highlights = @case_study.code_highlights.all
  end

  def new
    @code_highlight = @case_study.code_highlights.new
  end

  def create
    @code_highlight = @case_study.code_highlights.new(code_highlight_params)
    if @code_highlight.save
      redirect_to admin_case_study_code_highlights_url(@case_study)
    else
      render :new
    end
  end

  def edit
    @code_highlight = @case_study.code_highlights.find(params[:id])
  end

  def update
    @code_highlight = @case_study.code_highlights.find(params[:id])
    if @code_highlight.update(code_highlight_params)
      redirect_to admin_case_study_code_highlights_url(@case_study)
    else
      render :edit
    end
  end

  def destroy
    @code_highlight = @case_study.code_highlights.find(params[:id])
    @code_highlight.destroy
    redirect_to admin_case_study_code_highlights_url(@case_study)
  end

  private

  def load_case_study
    # params changed because of nested routing (:case_study_slug)
    @case_study = CaseStudy.find_by(slug: params[:case_study_slug])
  end

  def code_highlight_params
    params.require(:code_highlight).permit(:image, :caption, :position)
  end

end

app/views/admin/code_highlights/_form.html.haml
= simple_form_for(@code_highlight, url: [:admin, @case_study, @code_highlight]) do |f|
  = f.input :position
  = f.input :caption

  - if @code_highlight.image.present?
    = image_tag @code_highlight.image.url(:thumb)
    = link_to 'Original', @code_highlight.image.url
  = f.input :image, as: :file

  .form-group
    = f.submit class: "btn btn-primary"
    = link_to "Cancel", admin_case_study_code_highlights_url(@case_study), class: "btn btn-secondary"

app/views/admin/code_highlights/edit.html.haml
%h2 Editing Code Highlight

= render partial: 'form'

app/views/admin/code_highlights/index.html.haml
%h2 Code Highlights

= link_to 'New Code Highlight', new_admin_case_study_code_highlight_url(@case_study), class: 'btn btn-primary'

%table.table
  %tr
    %th Position
    %th Caption

  - @code_highlights.each do |code_highlight|
    %tr
      %td= code_highlight.position
      %td= code_highlight.caption
      %td
        = link_to("Edit", edit_admin_case_study_code_highlight_url(@case_study, code_highlight), class: 'btn btn-secondary')
        = link_to("Delete", admin_case_study_code_highlight_url(@case_study, code_highlight), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger')

app/views/admin/code_highlights/new.html.haml
%h2 New Code Highlight

= render partial: 'form'