config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  # Resources gives you portfolio_items/show and index but overrides the path to 'work'
  # Resources is for a thing that has a lot/ it's gonna be in the db
  resources :case_studies, only: [:show, :index], path: 'work', param: :slug
  # API route for video interactions
  resources :interactions, only: [:index, :create]

  # Custom routing: when you go to /contact, contacts#new handles the request
  get '/contact', to: 'contacts#new'
  post '/contacts', to: 'contacts#create'
  get '/about', to: 'pages#about'

  namespace :admin do
    root 'case_studies#index'
    resources :case_studies, param: :slug do
      resources :code_highlights
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  if Rails.env.development?
    mount Localtower::Engine, at: "localtower"
  end
end

app/views/layouts/admin.html.haml
!!! 5
%html
  %head
    %title Portfolio
    = csrf_meta_tags
    = action_cable_meta_tag

    = stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'admin', 'data-turbolinks-track' => 'reload'

  %body
    #admin-container
      .admin-nav
        %ul
          %li= link_to "Home", root_url
          %li= link_to "Case Studies", admin_case_studies_url
      .admin-main
        .container-fluid
          = yield

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Marian Serna | Portfolio
    = csrf_meta_tags
    = action_cable_meta_tag
    %meta{name: 'viewport', content: 'initial-scale=1.0'}
    %meta{charset: 'utf-8'}

    /[if lt IE 9]
      = javascript_include_tag 'html5shiv.min'

    %link{href:'https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js', rel: 'stylesheet'}
    %link{href:'https://fonts.googleapis.com/css?family=Abril+Fatface|Montserrat:200|Nixie+One', rel: 'stylesheet'}
    %link{href:'https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css', rel: 'stylesheet'}
    %link{href:'https://afeld.github.io/emoji-css/emoji.css', rel: 'stylesheet'}

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'

  %body
    = react_component("NavMenu", props: {}, prerender: false)

    = yield
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'